# Generated by Django 5.0.7 on 2026-08-19 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('CLASSIFIED', 'CLASSIFIED'), ('ROUTED', 'ROUTED'), ('ANSWERED', 'ANSWERED'), ('ESCALATED', 'ESCALATED'), ('RESOLVED', 'RESOLVED'), ('APPEALED', 'APPEALED'), ('REOPENED', 'REOPENED')], default='SUBMITTED', max_length=20)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='chat.conversation')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='tenancy.department')),
            ],
            options={
                'db_table': 'grievances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(default='system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievance_history', to='tenancy.department')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grievances.grievance')),
            ],
            options={
                'db_table': 'grievance_status_history',
                'ordering': ['created_at'],
            },
        ),
    ]
