# Generated by Django 5.0.7 on 2026-08-19 23:33

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.TextField(blank=True)),
                ('checksum', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenancy.department')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='ingestion.document')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenancy.department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.document')),
            ],
            options={
                'db_table': 'document_chunks',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('superseded_by__isnull', True)), fields=['department'], name='idx_documents_dept'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('department', 'source_url', 'checksum'), name='uniq_doc_dept_url_checksum'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['department'], name='idx_chunks_dept'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_chunk_doc_index'),
        ),
    ]
